apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mycertificate
  namespace: default
spec:
  dnsNames:
    - www.dikshantmali.ga
  secretName: mycertificate-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
